file(GLOB DOC_FILES "*.hpp")
file(MAKE_DIRECTORY "${PROJECT_DOC_DIR}/${PROJECT_NAME}")   
set(DOXYGEN_PROJECT_NAME ${PROJECT_NAME})
set(DOXYGEN_OUTPUT_DIRECTORY "${PROJECT_DOC_DIR}/${PROJECT_NAME}")
doxygen_add_docs(
  doc-${PROJECT_NAME}
  ALL
  ${DOC_FILES}
  )
